"""add timestamp to note

Revision ID: 517416ec5565
Revises: 
Create Date: 2025-09-28 23:27:44.784932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '517416ec5565'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
